export const theme = {
  primaryDark: "black",
  primaryLight: "white",
  primaryHover: "#343078",
  secondaryDark: "#c5c5c5",
  secondaryLight: "#f1f1f1",
  secondaryBorder: "#d81414",
  active: "green",
  border: "#9520d2",
  mobile: "576px",
  navbarHeight: "4rem",
  navbarBackgroundColor: "#2d2d2d",
  fontMenuLink: "1rem",
  fontFormMessage: "0.5rem",
  socialMediaIconColor: "green",
  socialMediaIconHover: "#b10000",
  footerHeight: "3rem",
};
